
---
- hosts: all
  vars:
    ntpserver: ntp.metas.ch
    # create password with:
    # python -c 'import crypt; print crypt.crypt("Questor123", "$1$SomeSalt$")'
    password: $1$SomeSalt$gYe2UKCdKRZzMsGT3AEaE/


  tasks:
    #
    # time - first get the system time right and in cron every hour
    #   we want accurate time for our logging processes
    #
  - name: install NTP and synchronise time
    apt: pkg=ntpdate state=present

  - name: configure NTP server to ntp.metas.ch
    copy: src=src/synctime.sh dest=/etc/cron.hourly mode=0744

  - name: synchronise time with NTP Server
    command: ntpdate {{ ntpserver }}

  - name: add users
    user: name={{ item }} state=present password=$password
    with_items:
        - qsapp
        - qsdevop
          # remote access user
        - 0mNaAeR@5Zzp83ZbNMJn

  - name: Install base server packages
    apt: pkg={{ item }} state=present
    with_items:
        - ntpdate
        - htop
        - vim
        - sudo
        - openssh-client
        - openssh-server
        - nfs-common
        - perl-doc
        - git


- hosts: app
  tasks:
  - name: nginx install
    apt: pkg=nginx state=present

  - name: nginx restart
    action: service name=nginx state=started

- hosts: broken
  tasks:
  - name: Install perltidy (for default system perl - sysperl)
    apt: pkg=perltidy state=present

- hosts: hidden
  tasks:
  - name: apache2 install
    apt: pkg=apache2 state=present

  - name: mysql-server install
    apt: pkg=mysql-server state=present

  - name: libmysqlclient-dev (mysql_config for DBD:Mysql)
    apt: pkg:libmysqlclient-dev state=present

  - name: php5 install
    apt: pkg=php5 state=present

  - name: php-pear install
    apt: pkg=php-pear state=present

  - name: php5-mysql install
    apt: pkg=php5-mysql state=present

  - name: nginx install
    apt: pkg=nginx state=present

