#!/bin/sh

cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 App::Ack
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 App::FatPacker
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 App::Todo
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Archive::Zip
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Catalyst::Runtime
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Catalyst::Devel
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Catalyst::Helper::Model::DBIC::Schema
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Catalyst::Helper::AuthDBIC
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Class::DBI
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Config::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Convert::NLS_DATE_FORMAT
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Dancer
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Date::Manip
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Date::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::DateManip
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::ISO8601
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::MSSQL
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::Pg
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::SQLite
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DateTime::Format::Strptime
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBD::ADO
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBD::ODBC
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBD::SQLite
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBIx::Class
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBIx::Class::Schema::Loader
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 DBIx::Class::TimeStamp
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Email::Find
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Email::Valid
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 File::HomeDir
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Finance::Quote
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Finance::YahooQuote
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 HTML::LinkExtractor
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 HTML::TagCloud
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 HTML::Tree
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 HTML::TreeBuilder::XPath
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 HTTP::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Image::ExifTool
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Image::Info
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Image::Magick
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 IO::Socket::SSL
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 JSON
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Mail::RFC822::Address
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Module::Starter
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Module::Starter::PBP
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Mojolicious
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Moose
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 MooseX::MarkAsMethods
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 MooseX::NonMoose
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Net::OAuth
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Net::Twitter
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 NetAddr::IP
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Number::Format
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 PAR
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 PAR::Packer
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Perl::Critic
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Perl::Tidy
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Plack
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Readonly
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Regexp::Common
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Regexp::Common::Email::Address
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Roman
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 SQL::Abstract
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 SQL::Translator
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Template
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Template::Plugin::Number::Format
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Text::Template
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Time::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Win32::Unicode
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 WWW::Mechanize
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 XML::Simple
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 XML::Twig
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 XMLRPC::Lite
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Modern::Perl
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Log::Log4perl::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Dancer2
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 PDF::Reuse
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 XML::Feed
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 URI::Escape
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 WordPress
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 File::Copy::Recursive
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Type::Tiny
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Mouse
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Mo
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Starman
cpanm --mirror-only --mirror file://mnt/cpan-13.10.0 Task::Plack

